In [16]:
import torch
import torch.nn as nn
import math

def positional_encoding(batch, time_len, var_len, d_model):
        pe = torch.zeros(batch, time_len, d_model).float()
        pe.require_grad = False

        position = torch.arange(0, time_len).float().unsqueeze(1)
        div_term = (torch.arange(0, d_model, 2).float() * -(math.log(10000.0) / d_model)).exp()

        pe[:, :, 0::2] = torch.sin(position * div_term)
        pe[:, :, 1::2] = torch.cos(position * div_term)

        return pe.repeat_interleave(var_len, dim=1)

In [17]:
print(positional_encoding(1, 3, 3, 10))

tensor([[[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
           1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00],
         [ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
           1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00],
         [ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
           1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00],
         [ 8.4147e-01,  5.4030e-01,  1.5783e-01,  9.8747e-01,  2.5116e-02,
           9.9968e-01,  3.9811e-03,  9.9999e-01,  6.3096e-04,  1.0000e+00],
         [ 8.4147e-01,  5.4030e-01,  1.5783e-01,  9.8747e-01,  2.5116e-02,
           9.9968e-01,  3.9811e-03,  9.9999e-01,  6.3096e-04,  1.0000e+00],
         [ 8.4147e-01,  5.4030e-01,  1.5783e-01,  9.8747e-01,  2.5116e-02,
           9.9968e-01,  3.9811e-03,  9.9999e-01,  6.3096e-04,  1.0000e+00],
         [ 9.0930e-01, -4.1615e-01,  3.1170e-01,  9.5018e-01,  5.0217e-02,
           9.9874e-

In [10]:
import torch

# Creating a dummy tensor for demonstration, replace this with your actual tensor
batch, time, var, hidden = 5, 10, 3, 4  # Example dimensions
tensor = torch.rand(batch, time, var, hidden)  # Random tensor for example

# Create a zeros tensor to insert
zeros_tensor = torch.zeros(batch, 1, var, hidden)

# Insert the zeros tensor at the first index of the time dimension
new_tensor = torch.cat((zeros_tensor, tensor[:, :-1, :, :]), dim=1)  # Removing last time index while concatenating

print(tensor)
print("--------")
print(new_tensor)

tensor([[[[8.1890e-02, 8.8884e-01, 1.6914e-01, 7.4296e-01],
          [2.9950e-01, 4.6841e-01, 6.7833e-01, 4.3450e-01],
          [2.6828e-01, 2.3228e-01, 7.9424e-01, 2.8804e-01]],

         [[5.7599e-01, 7.9061e-01, 3.4316e-01, 1.8674e-01],
          [1.6541e-01, 6.6050e-01, 7.1055e-01, 4.9033e-01],
          [8.3587e-01, 4.2750e-01, 7.1809e-01, 7.6841e-02]],

         [[3.4726e-01, 4.2610e-01, 4.3280e-01, 7.9391e-01],
          [5.9662e-01, 8.4239e-01, 9.8805e-01, 8.8960e-01],
          [3.6912e-01, 3.4132e-01, 1.9247e-01, 4.2013e-01]],

         [[1.8310e-01, 8.2774e-01, 9.4628e-01, 7.8454e-01],
          [7.6710e-02, 6.0990e-01, 4.3372e-01, 3.9776e-01],
          [1.9593e-01, 3.5578e-01, 8.8149e-01, 2.8150e-01]],

         [[9.8118e-01, 5.4203e-01, 8.1493e-03, 4.9602e-01],
          [4.8817e-01, 1.5491e-01, 7.5094e-01, 4.0846e-01],
          [7.4319e-01, 1.3771e-01, 1.0805e-01, 9.6939e-01]],

         [[2.2092e-01, 3.1865e-01, 1.7050e-01, 6.3920e-01],
          [9.8344e-01, 2.3785e

In [3]:
import torch
import math

def positional_encoding(batch, d_model, var_len, time_len):
        pe = torch.zeros(batch, time_len, d_model).float()
        pe.require_grad = False

        position = torch.arange(0, time_len).float().unsqueeze(1)
        div_term = (torch.arange(0, d_model, 2).float() * -(math.log(10000.0) / d_model)).exp()

        pe[:, :, 0::2] = torch.sin(position * div_term)
        pe[:, :, 1::2] = torch.cos(position * div_term)

        return pe.repeat_interleave(var_len, dim=1)

print(positional_encoding(2, 10, 2, 2))

tensor([[[0.0000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
          1.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00],
         [0.0000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
          1.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00],
         [8.4147e-01, 5.4030e-01, 1.5783e-01, 9.8747e-01, 2.5116e-02,
          9.9968e-01, 3.9811e-03, 9.9999e-01, 6.3096e-04, 1.0000e+00],
         [8.4147e-01, 5.4030e-01, 1.5783e-01, 9.8747e-01, 2.5116e-02,
          9.9968e-01, 3.9811e-03, 9.9999e-01, 6.3096e-04, 1.0000e+00]],

        [[0.0000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
          1.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00],
         [0.0000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
          1.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00],
         [8.4147e-01, 5.4030e-01, 1.5783e-01, 9.8747e-01, 2.5116e-02,
          9.9968e-01, 3.9811e-03, 9.9999e-01, 6.3096e-04, 1.0000e+00],
         [8